create table if not exists public.cha_casa_reservas (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  gift_name text not null,
  gift_index integer not null unique,
  created_at timestamptz not null default now(),
  constraint guest_name_not_empty check (length(trim(guest_name)) > 0),
  constraint gift_name_not_empty check (length(trim(gift_name)) > 0)
);

alter table public.cha_casa_reservas enable row level security;

drop policy if exists "public can view reservations" on public.cha_casa_reservas;
create policy "public can view reservations"
on public.cha_casa_reservas for select
to anon, authenticated
using (true);

drop policy if exists "public can create reservations" on public.cha_casa_reservas;
create policy "public can create reservations"
on public.cha_casa_reservas for insert
to anon, authenticated
with check (true);

-- Depois de executar, publique novamente o arquivo HTML.
