create table if not exists public.cha_casa_reservas (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  gift_name text not null,
  gift_index integer not null unique,
  created_at timestamptz not null default now(),
  constraint guest_name_not_empty check (length(trim(guest_name)) > 0),
  constraint gift_name_not_empty check (length(trim(gift_name)) > 0)
);

create table if not exists public.cha_casa_presentes (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  created_at timestamptz not null default now(),
  constraint gift_name_not_empty check (length(trim(name)) > 0),
  constraint gift_category_not_empty check (length(trim(category)) > 0),
  unique (name, category)
);

alter table public.cha_casa_reservas enable row level security;
alter table public.cha_casa_presentes enable row level security;

drop policy if exists "public can view reservations" on public.cha_casa_reservas;
create policy "public can view reservations"
on public.cha_casa_reservas for select
to anon, authenticated
using (true);

drop policy if exists "public can create reservations" on public.cha_casa_reservas;
create policy "public can create reservations"
on public.cha_casa_reservas for insert
to anon, authenticated
with check (true);

drop policy if exists "public can view gifts" on public.cha_casa_presentes;
create policy "public can view gifts"
on public.cha_casa_presentes for select
to anon, authenticated
using (true);

drop policy if exists "public can create gifts" on public.cha_casa_presentes;
create policy "public can create gifts"
on public.cha_casa_presentes for insert
to anon, authenticated
with check (true);

-- Depois de executar, publique novamente o arquivo HTML.
